[project]
name = "optimized-dev-experiences"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
